steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, --tag, "${_IMAGE}", .]
  - name: gcr.io/cloud-builders/docker
    args: [push, "${_IMAGE}"]
images: ["${_IMAGE}"]
serviceAccount: "projects/${PROJECT_ID}/serviceAccounts/leavenowbot-build@${PROJECT_ID}.iam.gserviceaccount.com"
options:
  logging: CLOUD_LOGGING_ONLY
